//! handoff.md 章节模型与渲染签名。
//!
//! Spec: docs/specs/handoff.md

use crate::artifact::Artifact;
use crate::design::guardrails::INLINE_STYLE_MARKER;
use crate::design::VisualBrief;

/// handoff.md 标准章节顺序（集成契约）。
pub const SECTIONS: [&str; 7] = [
    "Intent",
    "Artifact",
    "Files",
    "Design Notes",
    "How To Preview",
    "Next Steps",
    "Agent Notes",
];

/// 目标 Agent，影响 `Agent Notes` 的附注文案（不改变文件布局规则）。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HandoffAgent {
    Generic,
    OpenCode,
    ClaudeCode,
    Codex,
}

impl HandoffAgent {
    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "generic" => Some(Self::Generic),
            "opencode" => Some(Self::OpenCode),
            "claude-code" => Some(Self::ClaudeCode),
            "codex" => Some(Self::Codex),
            _ => None,
        }
    }
}

/// 渲染完整 handoff.md。M1 按标准章节实现。
pub fn render(artifact: &Artifact, agent: HandoffAgent) -> String {
    let title = artifact
        .root
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("artifact");
    let primary_file = artifact.kind.primary_file();
    let brief = VisualBrief::default_for(artifact.kind);
    let visual_brief = brief.as_str();
    let brief_direction = brief.direction();
    let recommended_patterns = brief.recommended_patterns().join("`, `");
    let root = artifact.root.display();

    format!(
        "# Handoff: {title}\n\n\
## Intent\n\n\
- Goal: continue shaping `{title}` into a previewable `{kind}` artifact.\n\
- Audience: humans and external agents editing plain files.\n\
- Current status: starter artifact generated by `odl`.\n\n\
## Artifact\n\n\
- Kind: `{kind}`.\n\
- Primary file: `{primary_file}`.\n\
- Root: `{root}`.\n\n\
## Files\n\n\
- `{primary_file}`: main preview content.\n\
- `manifest.json`: artifact metadata and design kernel settings.\n\
- `handoff.md`: this handoff note.\n\
- `assets/od-design.css`: shared design kernel stylesheet when present.\n\n\
## Design Notes\n\n\
- Visual brief: `{visual_brief}` — {brief_direction}.\n\
- Prefer these pattern recipes for this brief: `{recommended_patterns}`.\n\
- Style source: link `assets/od-design.css` or inline `<style {inline_marker}>`.\n\
- Use `--od-*` CSS variables and `od-*` primitive/recipe/pattern classes; do not introduce a new global token prefix.\n\
- Avoid AI-slop defaults: no blue-to-purple gradients, glassmorphism, random icons, remote fonts, or CDN UI kits.\n\
- Keep the artifact previewable as plain files; do not add Tailwind, React, shadcn/ui, or a dev server unless a downstream adapter explicitly requires it.\n\n\
## How To Preview\n\n\
- **Coding agents (Open Design MCP):** call MCP tool `artifact_preview` with `dir` set to this artifact root. Keep defaults (`externalBrowser` false, `watch` true) so the persistent live-reloading preview window opens. Do **not** open a system browser yourself (`start`, `xdg-open`, `open`, Playwright, etc.).\n\
- **CLI / humans:** run `odl preview {root}`, or from the artifact directory run `odl preview .`.\n\n\
## Next Steps\n\n\
- Clarify the user goal, audience, and final delivery format.\n\
- Edit `{primary_file}` directly and keep paths relative to the artifact root.\n\
- Re-run preview after changes and update this handoff with any important decisions.\n\n\
## Agent Notes\n\n\
{}\n",
        agent_notes(agent),
        kind = artifact.kind.slug(),
        inline_marker = INLINE_STYLE_MARKER,
    )
}

/// M0 兼容：最小占位 handoff，保持 `odl new` 现有行为直到 M1 完整渲染上线。
pub fn minimal_stub() -> &'static str {
    "# Handoff\n\nDescribe intent, constraints, and next agent steps here.\n"
}

fn agent_notes(agent: HandoffAgent) -> &'static str {
    match agent {
        HandoffAgent::Generic => GENERIC_AGENT_NOTES,
        HandoffAgent::OpenCode => {
            "You can edit the files directly. Preserve the artifact layout and keep paths relative to the artifact root. If you add assets, place them under `assets/`. To preview, call MCP `artifact_preview` on this directory (do not open a system browser yourself); humans/scripts may use `odl preview .`. For OpenCode, prefer small patches and avoid adding runtime dependencies unless the artifact explicitly needs them."
        }
        HandoffAgent::ClaudeCode => {
            "You can edit the files directly. Preserve the artifact layout and keep paths relative to the artifact root. If you add assets, place them under `assets/`. To preview, call MCP `artifact_preview` on this directory (do not open a system browser yourself); humans/scripts may use `odl preview .`. For Claude Code, keep generated sections easy for humans to review and update."
        }
        HandoffAgent::Codex => {
            "You can edit the files directly. Preserve the artifact layout and keep paths relative to the artifact root. If you add assets, place them under `assets/`. To preview, call MCP `artifact_preview` on this directory (do not open a system browser yourself); humans/scripts may use `odl preview .`. For Codex, avoid project-wide rewrites when a focused artifact edit is enough."
        }
    }
}

const GENERIC_AGENT_NOTES: &str = "You can edit the files directly. Preserve the artifact layout and keep paths relative to the artifact root. If you add assets, place them under `assets/`. To preview, call MCP `artifact_preview` on this directory (do not open a system browser yourself); humans/scripts may use `odl preview .`.";

#[cfg(test)]
mod tests {
    use super::*;
    use crate::artifact::ArtifactKind;
    use std::path::PathBuf;

    #[test]
    fn render_contains_standard_sections_and_constraints() {
        let artifact = Artifact::new(ArtifactKind::Html, PathBuf::from("demo"));
        let rendered = render(&artifact, HandoffAgent::Generic);

        for section in SECTIONS {
            assert!(rendered.contains(&format!("## {section}")));
        }
        assert!(rendered.contains("`index.html`"));
        assert!(rendered.contains("`odl preview .`"));
        assert!(rendered.contains("artifact_preview"));
        assert!(rendered.contains("Do **not** open a system browser"));
        assert!(rendered.contains("`--od-*` CSS variables"));
        assert!(rendered.contains("assets/od-design.css"));
    }

    #[test]
    fn parses_agent_slug() {
        assert_eq!(
            HandoffAgent::parse("opencode"),
            Some(HandoffAgent::OpenCode)
        );
        assert_eq!(HandoffAgent::parse("unknown"), None);
    }
}
